# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yarado-supporter-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yarasupporter.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_347e8faf187a4947a1aae0f796fee4c6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d6a961ca70cd425ebc5d2dae4f773723 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yarasupporter.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_347e8faf187a4947a1aae0f796fee4c6 }}/supporter:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yarado-supporter-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5d8178b13c424bddb87c4f3330c77f3d }}
        images: 'yarasupporter.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_347e8faf187a4947a1aae0f796fee4c6 }}/supporter:${{ github.sha }}'